from lib.modules.common import *
from lib.modules.purchase_item_check import *

def output(pull_url,output):
    output.insert('end','---チェック開始---','info')
    driver = driver_init(pull_url)
    output.insert('end','\n◎What,Why,gyazo,差分なし,マージ済','info')
    #Conversationチェック(conflict以外)
    output_error(output, conversation_check(driver))
    #商品購入
    driver.get(pull_url + '/files')
    output.insert('end','\n◎商品コントローラー','info')
    output_error(output, check_items_c(driver))  
    output.insert('end','\n◎購入コントローラー','info')
    output_error(output, check_orders_c(driver))
    output.insert('end','\n◎payjpのjs','info')
    output_error(output, check_card_j(driver))
    f_messages,messages = check_form_m(driver)
    output.insert('end','\n◎formオブジェクト','info')
    output_error(output, f_messages)
    output.insert('end','\n◎購入履歴・住所モデル','info')
    output_error(output, messages)
    output.insert('end','\n◎ユーザーモデル','info')
    output_error(output, check_user_m(driver))
    output.insert('end','\n◎商品モデル','info')
    output_error(output, check_item_m(driver))
    output.insert('end','\n◎トップページの売り切れ表示','info')
    output_error(output, check_top_v(driver))
    output.insert('end','\n◎詳細ページの売り切れ表示','info')
    output_error(output, check_show_v(driver))
    output.insert('end','\n◎購入ページ','info')
    output_error(output, check_order_v(driver))
    output.insert('end','\n◎ルーティング','info')
    output_error(output, check_routes(driver))
    output.insert('end','\n◎マイグレーション','info')
    output_error(output, check_order_mig(driver))
    output.insert('end','\n◎factorybot','info')
    output_error(output, check_order_f(driver))
    output.insert('end','\n◎単体テスト','info')
    output_error(output, check_order_t(driver))
    output.insert('end','\n◎その他','info')
    output_error(output, check_others(driver))
    output.insert('end','\n---チェック終了---','info')
    driver.quit()